sudo: required

services:
  - docker

before_install:
  - docker build -t spikelabs/corebos-admin-test -f ./deployment/Dockerfile .

script:
  - docker run spikelabs/corebos-admin-test php -v

after_success:
  - docker build -t spikelabs/corebos-admin -f ./deployment/Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push spikelabs/corebos-admin
