<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubernetes.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>CreateClientRequest</code>
 */
class CreateClientRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Deployment deployment = 1;</code>
     */
    private $deployment = null;
    /**
     * Generated from protobuf field <code>.Service service = 2;</code>
     */
    private $service = null;
    /**
     * Generated from protobuf field <code>.DeploymentPvc deployment_pvc = 3;</code>
     */
    private $deployment_pvc = null;
    /**
     * Generated from protobuf field <code>.Ingress ingress = 4;</code>
     */
    private $ingress = null;
    /**
     * Generated from protobuf field <code>.Database database = 5;</code>
     */
    private $database = null;
    /**
     * Generated from protobuf field <code>.DatabaseService database_service = 6;</code>
     */
    private $database_service = null;
    /**
     * Generated from protobuf field <code>.DatabasePvc database_pvc = 7;</code>
     */
    private $database_pvc = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Deployment $deployment
     *     @type \Service $service
     *     @type \DeploymentPvc $deployment_pvc
     *     @type \Ingress $ingress
     *     @type \Database $database
     *     @type \DatabaseService $database_service
     *     @type \DatabasePvc $database_pvc
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubernetes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Deployment deployment = 1;</code>
     * @return \Deployment
     */
    public function getDeployment()
    {
        return $this->deployment;
    }

    /**
     * Generated from protobuf field <code>.Deployment deployment = 1;</code>
     * @param \Deployment $var
     * @return $this
     */
    public function setDeployment($var)
    {
        GPBUtil::checkMessage($var, \Deployment::class);
        $this->deployment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Service service = 2;</code>
     * @return \Service
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>.Service service = 2;</code>
     * @param \Service $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkMessage($var, \Service::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DeploymentPvc deployment_pvc = 3;</code>
     * @return \DeploymentPvc
     */
    public function getDeploymentPvc()
    {
        return $this->deployment_pvc;
    }

    /**
     * Generated from protobuf field <code>.DeploymentPvc deployment_pvc = 3;</code>
     * @param \DeploymentPvc $var
     * @return $this
     */
    public function setDeploymentPvc($var)
    {
        GPBUtil::checkMessage($var, \DeploymentPvc::class);
        $this->deployment_pvc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Ingress ingress = 4;</code>
     * @return \Ingress
     */
    public function getIngress()
    {
        return $this->ingress;
    }

    /**
     * Generated from protobuf field <code>.Ingress ingress = 4;</code>
     * @param \Ingress $var
     * @return $this
     */
    public function setIngress($var)
    {
        GPBUtil::checkMessage($var, \Ingress::class);
        $this->ingress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Database database = 5;</code>
     * @return \Database
     */
    public function getDatabase()
    {
        return $this->database;
    }

    /**
     * Generated from protobuf field <code>.Database database = 5;</code>
     * @param \Database $var
     * @return $this
     */
    public function setDatabase($var)
    {
        GPBUtil::checkMessage($var, \Database::class);
        $this->database = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DatabaseService database_service = 6;</code>
     * @return \DatabaseService
     */
    public function getDatabaseService()
    {
        return $this->database_service;
    }

    /**
     * Generated from protobuf field <code>.DatabaseService database_service = 6;</code>
     * @param \DatabaseService $var
     * @return $this
     */
    public function setDatabaseService($var)
    {
        GPBUtil::checkMessage($var, \DatabaseService::class);
        $this->database_service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.DatabasePvc database_pvc = 7;</code>
     * @return \DatabasePvc
     */
    public function getDatabasePvc()
    {
        return $this->database_pvc;
    }

    /**
     * Generated from protobuf field <code>.DatabasePvc database_pvc = 7;</code>
     * @param \DatabasePvc $var
     * @return $this
     */
    public function setDatabasePvc($var)
    {
        GPBUtil::checkMessage($var, \DatabasePvc::class);
        $this->database_pvc = $var;

        return $this;
    }

}

