<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubernetes.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>DeleteClientRequest</code>
 */
class DeleteClientRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string deployment_name = 1;</code>
     */
    private $deployment_name = '';
    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     */
    private $service_name = '';
    /**
     * Generated from protobuf field <code>string deployment_pvc_name = 3;</code>
     */
    private $deployment_pvc_name = '';
    /**
     * Generated from protobuf field <code>string ingress_name = 4;</code>
     */
    private $ingress_name = '';
    /**
     * Generated from protobuf field <code>string database_name = 5;</code>
     */
    private $database_name = '';
    /**
     * Generated from protobuf field <code>string database_service_name = 6;</code>
     */
    private $database_service_name = '';
    /**
     * Generated from protobuf field <code>string database_pvc_name = 7;</code>
     */
    private $database_pvc_name = '';
    /**
     * Generated from protobuf field <code>string configData = 8;</code>
     */
    private $configData = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $deployment_name
     *     @type string $service_name
     *     @type string $deployment_pvc_name
     *     @type string $ingress_name
     *     @type string $database_name
     *     @type string $database_service_name
     *     @type string $database_pvc_name
     *     @type string $configData
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubernetes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string deployment_name = 1;</code>
     * @return string
     */
    public function getDeploymentName()
    {
        return $this->deployment_name;
    }

    /**
     * Generated from protobuf field <code>string deployment_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDeploymentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->deployment_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * Generated from protobuf field <code>string service_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deployment_pvc_name = 3;</code>
     * @return string
     */
    public function getDeploymentPvcName()
    {
        return $this->deployment_pvc_name;
    }

    /**
     * Generated from protobuf field <code>string deployment_pvc_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDeploymentPvcName($var)
    {
        GPBUtil::checkString($var, True);
        $this->deployment_pvc_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ingress_name = 4;</code>
     * @return string
     */
    public function getIngressName()
    {
        return $this->ingress_name;
    }

    /**
     * Generated from protobuf field <code>string ingress_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIngressName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ingress_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string database_name = 5;</code>
     * @return string
     */
    public function getDatabaseName()
    {
        return $this->database_name;
    }

    /**
     * Generated from protobuf field <code>string database_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDatabaseName($var)
    {
        GPBUtil::checkString($var, True);
        $this->database_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string database_service_name = 6;</code>
     * @return string
     */
    public function getDatabaseServiceName()
    {
        return $this->database_service_name;
    }

    /**
     * Generated from protobuf field <code>string database_service_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDatabaseServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->database_service_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string database_pvc_name = 7;</code>
     * @return string
     */
    public function getDatabasePvcName()
    {
        return $this->database_pvc_name;
    }

    /**
     * Generated from protobuf field <code>string database_pvc_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDatabasePvcName($var)
    {
        GPBUtil::checkString($var, True);
        $this->database_pvc_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string configData = 8;</code>
     * @return string
     */
    public function getConfigData()
    {
        return $this->configData;
    }

    /**
     * Generated from protobuf field <code>string configData = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setConfigData($var)
    {
        GPBUtil::checkString($var, True);
        $this->configData = $var;

        return $this;
    }

}

