<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubernetes.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>Deployment</code>
 */
class Deployment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 replicas = 1;</code>
     */
    private $replicas = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string label = 3;</code>
     */
    private $label = '';
    /**
     * Generated from protobuf field <code>string db_host = 4;</code>
     */
    private $db_host = '';
    /**
     * Generated from protobuf field <code>string db_username = 5;</code>
     */
    private $db_username = '';
    /**
     * Generated from protobuf field <code>string db_password = 6;</code>
     */
    private $db_password = '';
    /**
     * Generated from protobuf field <code>string db_database = 7;</code>
     */
    private $db_database = '';
    /**
     * Generated from protobuf field <code>string site_url = 8;</code>
     */
    private $site_url = '';
    /**
     * Generated from protobuf field <code>string image = 9;</code>
     */
    private $image = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $replicas
     *     @type string $name
     *     @type string $label
     *     @type string $db_host
     *     @type string $db_username
     *     @type string $db_password
     *     @type string $db_database
     *     @type string $site_url
     *     @type string $image
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubernetes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 replicas = 1;</code>
     * @return int
     */
    public function getReplicas()
    {
        return $this->replicas;
    }

    /**
     * Generated from protobuf field <code>int32 replicas = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setReplicas($var)
    {
        GPBUtil::checkInt32($var);
        $this->replicas = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string label = 3;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_host = 4;</code>
     * @return string
     */
    public function getDbHost()
    {
        return $this->db_host;
    }

    /**
     * Generated from protobuf field <code>string db_host = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDbHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_username = 5;</code>
     * @return string
     */
    public function getDbUsername()
    {
        return $this->db_username;
    }

    /**
     * Generated from protobuf field <code>string db_username = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDbUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_password = 6;</code>
     * @return string
     */
    public function getDbPassword()
    {
        return $this->db_password;
    }

    /**
     * Generated from protobuf field <code>string db_password = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDbPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_database = 7;</code>
     * @return string
     */
    public function getDbDatabase()
    {
        return $this->db_database;
    }

    /**
     * Generated from protobuf field <code>string db_database = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDbDatabase($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_database = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string site_url = 8;</code>
     * @return string
     */
    public function getSiteUrl()
    {
        return $this->site_url;
    }

    /**
     * Generated from protobuf field <code>string site_url = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image = 9;</code>
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>string image = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->image = $var;

        return $this;
    }

}

